### ISSUE TITLE
Rerunning Sandstorm results in slower and slower performance

### ISSUE THREAD

**Issue by liyanchang** [Ink/codeblock.js#1]
To duplicate:
1. Run Sandstorm.
2. Hit Refresh
3. Repeat ~3 times before the speed is noticeable slower.

**Comment by brettcvz** [comment]
This is dues to a memory/cpu "leak" because when you press reset it doesn't run "clearInterval". This could be done via introspection on the code to "undo" any running intervals/timeouts when the reset button is pressed, but the notion of "reset" is to reset the text, not reset the code, so leaving as is.
